# Generated by Django 3.2.19 on 2023-06-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0004_alter_cryptocurrency_price_change_24h'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['-market_cap']},
        ),
    ]
