# Generated by Django 3.2.19 on 2023-06-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0005_alter_cryptocurrency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('asset_platform_id', models.CharField(max_length=255, null=True)),
                ('block_time_in_minutes', models.PositiveIntegerField(default=0)),
                ('categories', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('homepage', models.JSONField(default=list)),
                ('blockchain_site', models.JSONField(default=list)),
                ('market_cap_rank', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
