# Generated by Django 3.2.19 on 2023-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0008_auto_20230613_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='blockchain_site',
            field=models.JSONField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coins',
            name='homepage',
            field=models.JSONField(max_length=10, null=True),
        ),
    ]
