# Generated by Django 3.2.19 on 2023-06-15 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0012_auto_20230615_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceupdate',
            old_name='coin',
            new_name='coin_id',
        ),
    ]
