# Generated by Django 3.2.19 on 2023-06-11 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_backend", "0005_alter_cryptocurrency_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portifolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(null=True)),
                (
                    "cryptocurrency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_backend.cryptocurrency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "holdings",
                    models.ManyToManyField(
                        through="portifolio.Holding", to="api_backend.CryptoCurrency"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="holding",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portifolio.portfolio"
            ),
        ),
    ]
