# Generated by Django 3.2.19 on 2023-06-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_userpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
