# Generated by Django 3.2.19 on 2023-06-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_alter_credits_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='holding',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
